### ISSUE TITLE
The name org.gnome.Shell.Screencast was not provided by any .service files

### ISSUE THREAD

**Issue by ssalenik** [xlmnxp/blue-recorder#1]
Got this compiled on Ubuntu 20.10 (Wayland) and getting this when trying to start a recording:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MethodError("org.freedesktop.DBus.Error.ServiceUnknown", Some("The name org.gnome.Shell.Screencast was not provided by any .service files"), Msg { type: Error, sender: "org.freedesktop.DBus", reply-serial: 2, body: Signature: [
	s (115),
] })', src/ffmpeg_interface.rs:320:18
```

Possibly related to screencast just being broken in 20.10, but was wondering if maybe its just some dependency that I'm missing...

Thanks.

**Comment by xlmnxp** [comment]
> Got this compiled on Ubuntu 20.10 (Wayland) and getting this when trying to start a recording:
> 
> ```
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MethodError("org.freedesktop.DBus.Error.ServiceUnknown", Some("The name org.gnome.Shell.Screencast was not provided by any .service files"), Msg { type: Error, sender: "org.freedesktop.DBus", reply-serial: 2, body: Signature: [
> 	s (115),
> ] })', src/ffmpeg_interface.rs:320:18
> ```
> 
> Possibly related to screencast just being broken in 20.10, but was wondering if maybe its just some dependency that I'm missing...
> 
> Thanks.
That issue mentioned in this discussion
https://forum.snapcraft.io/t/can-i-use-org-gnome-shell-screencast-dbus-for-wayland-support/22883/6
Maybe Canonical disable this future in 20.10 but it back to 21.04

**Comment by ssalenik** [comment]
Sigh... seems like I can't get any screen recorder to work with 20.10 and Wayland... I guess I will have to wait for 21.04.
Thanks!

**Comment by xlmnxp** [comment]
> Sigh... seems like I can't get any screen recorder to work with 20.10 and Wayland... I guess I will have to wait for 21.04.
> Thanks!

Try install xdg-desktop-portal

**Comment by ssalenik** [comment]
Seems it was already installed when I tested.

**Comment by xlmnxp** [comment]
> Seems it was already installed when I tested.

Can you use d-feet and search in sessions for 
- `org.gnome.Shell.Screencast`
- `org.freedesktop.portal.ScreenCast` 
- `org.gnome.Mutter.ScreenCast`

if there anyone of them available?

**Comment by ssalenik** [comment]
No, none of those.

**Comment by xlmnxp** [comment]
> No, none of those.

this issue relate to this bug only in `ubuntu 20.10`
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1901391

Daniel van Vugt said `Fix released in mutter 3.38.3-2ubuntu1 (not gnome-shell)`
which version mutter in your system?

**Comment by ssalenik** [comment]
I have `3.38.2-1ubuntu1~20.10.1`, don't see an update yet... I wonder if it will be ported to 20.10

**Comment by xlmnxp** [comment]
maybe it not backported to 20.10 but we should wait few days and wait
they release the fix 2 days ago

**Comment by xlmnxp** [comment]
@ssalenik can you update your packages and try now?

**Comment by ssalenik** [comment]
20.10 still seem to be on the same version:
https://packages.ubuntu.com/search?keywords=mutter

`3.38.3` is only in hirsute

**Comment by xlmnxp** [comment]
> 20.10 still seem to be on the same version:
> https://packages.ubuntu.com/search?keywords=mutter
> 
> `3.38.3` is only in hirsute

I asked them in bug report to backport the fix to ubuntu 20.10

**Comment by xlmnxp** [comment]
they're said they cannot backport it because there package not in main repos for ubuntu 20.10

**Comment by ssalenik** [comment]
Ok, thanks. I guess I will have to wait another month ;)

**Comment by xlmnxp** [comment]
> Ok, thanks. I guess I will have to wait another month ;)

Until Ubuntu 21.04 😄

**Comment by xlmnxp** [comment]
> Ok, thanks. I guess I will have to wait another month ;)

Until Ubuntu 21.04 😄

**Comment by xlmnxp** [comment]
> Ok, thanks. I guess I will have to wait another month ;)

Ubuntu 21.04 released
Blue Recorder should work fine

**Comment by ssalenik** [comment]
Yup, I'm able to record now! :)
