### ISSUE TITLE
turkish language support

### ISSUE THREAD

**Issue by usnotv** [xlmnxp/blue-recorder#11]
turkish language support https://github.com/usolmz/blue-recorder/pull/2

**Comment by xlmnxp** [comment]
> turkish language support [usolmz#2](https://github.com/usolmz/blue-recorder/pull/2)

It already supported, what changes you want to do?

**Comment by usolmz** [comment]
https://github.com/usolmz/blue-recorder/blob/master/po/tr.po

**Comment by xlmnxp** [comment]
Turkish already exists
it relate to #10 gettext not work correctly
