### ISSUE TITLE
Blue Recorder not recording under Gnome (Wayland) anymore

### ISSUE THREAD

**Issue by me00001** [xlmnxp/blue-recorder#18]
> No, it's not in the directory.
> 
> Before there was a 0 KB temp file, but I cannot reproduce a situation where it's being created any more.

Something has changed in Gnome Shell or Blue Recorder, i found error come from pipewire with `journalctl -f` command  

The error comes after pressing the record button, happening with  building from source or Flatpak build with the same error 

<pre>مايو 21 15:24:39 me dbus-daemon[1071]: [session uid=1000 pid=1071] Activating service name=&apos;org.gnome.Shell.Screencast&apos; requested by &apos;:1.766&apos; (uid=1000 pid=299426 comm=&quot;./target/release/blue-recorder &quot;)
مايو 21 15:24:39 me dbus-daemon[1071]: [session uid=1000 pid=1071] Successfully activated service &apos;org.gnome.Shell.Screencast&apos;
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 2        (Spa:Enum:MediaType:video)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:None, flags 00000000 20 4</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Id 2        (Spa:Enum:VideoFormat:I420)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16x16</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16x16</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16383x16383</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 2147483647/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:None, flags 00000000 24 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 2        (Spa:Enum:MediaType:video)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 8        (Spa:Enum:VideoFormat:BGRx)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Rectangle 1920x1080</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 1/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>(34.0 -&gt; 37.0) negotiating -&gt; error (no more input formats)</b></font>
مايو 21 15:24:39 me pipewire-media-session[1739]: <font color="#D7D75F"><b>can&apos;t link 34:35 -&gt; 37:38: no more input formats</b></font>
مايو 21 15:24:39 me pipewire-media-session[1739]: <font color="#D7D75F"><b>error id:31 seq:1143 res:-22 (Invalid argument): no more input formats</b></font>
مايو 21 15:24:41 me dbus-daemon[1071]: [session uid=1000 pid=1071] Activating via systemd: service name=&apos;org.freedesktop.Tracker3.Miner.Extract&apos; unit=&apos;tracker-extract-3.service&apos; requested by &apos;:1.144&apos; (uid=1000 pid=9009 comm=&quot;/usr/lib/tracker-miner-fs-3 &quot;)
</pre>

After pressing stop recording the app is freezing

<pre><font color="#3465A4">master </font><font color="#CC0000">✗</font> <b>$</b> <font color="#4E9A06">./target/release/blue-recorder</font>                                                   <font color="#CC0000">137 ↵</font>
ffmpeg version n4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
<span style="background-color:#2E3436"><font color="#FFFF00">Guessed Channel Layout for Input Stream #0.0 : stereo</font></span>
Input #0, pulse, from &apos;default&apos;:
  Duration: N/A, start: 1625634342.032809, bitrate: 1536 kb/s
  Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -&gt; #0:0 (pcm_s16le (native) -&gt; vorbis (libvorbis))
Press [q] to stop, [?] for help
Output #0, ogg, to &apos;/home/suliman/الفيديو/2021-07-07 05:05:41.787298954.mkv.temp.audio&apos;:
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.134.100 libvorbis
size=     140kB time=00:00:12.57 bitrate=  91.0kbits/s speed=1.19x    
video:0kB audio:135kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 3.599206%
Exiting normally, received signal 15.

</pre>

_Originally posted by @me00001 in https://github.com/xlmnxp/blue-recorder/issues/8#issuecomment-845925907_

**Comment by xlmnxp** [comment]
I will check it and try to fix it

**Comment by xlmnxp** [comment]
@me00001 is the recorder mark in Gnome disappear when you stop the recording?

**Comment by me00001** [comment]
> @me00001 is the recorder mark in Gnome disappear when you stop the recording?

No, the mark still there

**Comment by xlmnxp** [comment]
> > @me00001 is the recorder mark in Gnome disappear when you stop the recording?
> 
> No, the mark still there

the issue from zvariant & zbus, I will work to fix it

**Comment by xlmnxp** [comment]
@me00001 I update `cargo.toml` with new releases of zbus and zvariant
can you to it in Wayland?

**Comment by me00001** [comment]
> @me00001 I update `cargo.toml` with new releases of zbus and zvariant can you to it in Wayland?

Blue Recorder still not recording under GNOME 40, GNOME 38 is fine.

**Comment by me00001** [comment]
logs from Fedora 34 in virtual machine  (GNOME 40.5 Wayland) after the app freezes, also got the same error with other distros that have Gnome 40 like Gentoo

#### Minimal log  :
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/ffmpeg_interface.rs:368:18`

#### Full logs 
`$ journalctl -f`
<pre>ديسمبر 01 16:18:29 fedora systemd[1]: Started Hostname Service.
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>pw.context: params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Id 2        (Spa:Enum:MediaType:video)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Choice: type Spa:Enum:Choice:None, flags 00000000 20 4</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Id 2        (Spa:Enum:VideoFormat:I420)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Rectangle 16x16</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Rectangle 16x16</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Rectangle 16383x16383</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 0/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 0/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 2147483647/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Choice: type Spa:Enum:Choice:None, flags 00000000 24 8</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 60/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>pw.context: params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default: Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Id 2        (Spa:Enum:MediaType:video)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Id 8        (Spa:Enum:VideoFormat:BGRx)</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Rectangle 1600x900</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Fraction 0/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 60/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 1/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>default:       Fraction 60/1</b></font>
ديسمبر 01 16:18:31 fedora pipewire[2225]: <font color="#CF6A4C"><b>pw.link: (58.0 -&gt; 60.0) negotiating -&gt; error (no more input formats)</b></font>
ديسمبر 01 16:18:33 fedora systemd[1502]: Starting Tracker metadata extractor...
ديسمبر 01 16:18:33 fedora systemd[1502]: Started Tracker metadata extractor.
ديسمبر 01 16:18:59 fedora systemd[1]: systemd-hostnamed.service: Deactivated successfully.
ديسمبر 01 16:18:59 fedora audit[1]: <font color="#7587A6">SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=systemd-hostnamed comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;</font>
ديسمبر 01 16:18:59 fedora audit: <font color="#7587A6">BPF prog-id=0 op=UNLOAD</font>
ديسمبر 01 16:18:59 fedora audit: <font color="#7587A6">BPF prog-id=0 op=UNLOAD</font>
ديسمبر 01 16:19:02 fedora audit[4600]: <font color="#7587A6">ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=4600 comm=&quot;blue-recorder&quot; exe=&quot;/home/suliman/blue-recorder/target/release/blue-recorder&quot; sig=11 res=1</font>
ديسمبر 01 16:19:02 fedora kernel: blue-recorder[4600]: segfault at 45 ip 00007efeedb56354 sp 00007ffde57dc6e0 error 4 in libgobject-2.0.so.0.6800.4[7efeedb34000+30000]
ديسمبر 01 16:19:02 fedora kernel: Code: a8 02 00 48 85 c0 0f 84 8d f1 ff ff 8b 4c 24 58 48 8b 54 24 20 eb 13 0f 1f 80 00 00 00 00 48 8b 00 48 85 c0 0f 84 6f f1 ff ff &lt;48&gt; 3b 50 08 75 ee 3b 48 10 75 e9 8b 74 24 48 3b 70 14 75 e0 c7 40
ديسمبر 01 16:19:02 fedora audit: <font color="#7587A6">BPF prog-id=70 op=LOAD</font>
ديسمبر 01 16:19:02 fedora audit: <font color="#7587A6">BPF prog-id=71 op=LOAD</font>
ديسمبر 01 16:19:02 fedora audit: <font color="#7587A6">BPF prog-id=72 op=LOAD</font>
ديسمبر 01 16:19:02 fedora systemd[1]: Started Process Core Dump (PID 4659/UID 0).
ديسمبر 01 16:19:02 fedora audit[1]: <font color="#7587A6">SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=systemd-coredump@3-4659-0 comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;</font>
ديسمبر 01 16:19:02 fedora systemd-coredump[4660]: Removed old coredump core.blue-recorder.1000.fe0c8b8e6cb343ae82d2a62659dcb9fc.4499.1638393395000000.zst.
ديسمبر 01 16:19:03 fedora systemd-coredump[4660]: [🡕] <font color="#CF6A4C"><b>Process 4600 (blue-recorder) of user 1000 dumped core.</b></font>
                                                        
                                                        <font color="#CF6A4C"><b>Stack trace of thread 4600:</b></font>
                                                        <font color="#CF6A4C"><b>#0  0x00007efeedb56354 signal_emit_unlocked_R (libgobject-2.0.so.0 + 0x30354)</b></font>
                                                        <font color="#CF6A4C"><b>#1  0x00007efeedb5776a g_signal_emit_valist (libgobject-2.0.so.0 + 0x3176a)</b></font>
                                                        <font color="#CF6A4C"><b>#2  0x00007efeedb57983 g_signal_emit (libgobject-2.0.so.0 + 0x31983)</b></font>
                                                        <font color="#CF6A4C"><b>#3  0x00007efeee3b1ac0 gtk_widget_dispose.lto_priv.0 (libgtk-3.so.0 + 0x3a9ac0)</b></font>
                                                        <font color="#CF6A4C"><b>#4  0x00007efeedb46a94 g_object_unref (libgobject-2.0.so.0 + 0x20a94)</b></font>
                                                        <font color="#CF6A4C"><b>#5  0x00007efeeda2b332 g_hash_table_remove_all_nodes.part.0 (libglib-2.0.so.0 + 0x3f332)</b></font>
                                                        <font color="#CF6A4C"><b>#6  0x00007efeeda2bf93 g_hash_table_remove_all (libglib-2.0.so.0 + 0x3ff93)</b></font>
                                                        <font color="#CF6A4C"><b>#7  0x00007efeeda30022 g_hash_table_destroy (libglib-2.0.so.0 + 0x44022)</b></font>
                                                        <font color="#CF6A4C"><b>#8  0x00007efeee135734 gtk_builder_finalize (libgtk-3.so.0 + 0x12d734)</b></font>
                                                        <font color="#CF6A4C"><b>#9  0x00007efeedb46b18 g_object_unref (libgobject-2.0.so.0 + 0x20b18)</b></font>
                                                        <font color="#CF6A4C"><b>#10 0x000055b98c73d1fe n/a (/home/suliman/blue-recorder/target/release/blue-recorder + 0xad1fe)</b></font>
ديسمبر 01 16:19:03 fedora abrt-dump-journal-core[823]: Failed to obtain all required information from journald
ديسمبر 01 16:19:03 fedora systemd[1]: systemd-coredump@3-4659-0.service: Deactivated successfully.
ديسمبر 01 16:19:03 fedora audit[1]: <font color="#7587A6">SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=&apos;unit=systemd-coredump@3-4659-0 comm=&quot;systemd&quot; exe=&quot;/usr/lib/systemd/systemd&quot; hostname=? addr=? terminal=? res=success&apos;</font>
ديسمبر 01 16:19:03 fedora audit: <font color="#7587A6">BPF prog-id=0 op=UNLOAD</font>
ديسمبر 01 16:19:03 fedora audit: <font color="#7587A6">BPF prog-id=0 op=UNLOAD</font>
ديسمبر 01 16:19:03 fedora audit: <font color="#7587A6">BPF prog-id=0 op=UNLOAD</font>
ديسمبر 01 16:19:03 fedora abrt-server[4672]: <font color="#D7D75F"><b>Executable &apos;/home/suliman/blue-recorder/target/release/blue-recorder&apos; doesn&apos;t belong to any package and ProcessUnpackaged is set to &apos;no&apos;</b></font>
ديسمبر 01 16:19:03 fedora abrt-server[4672]: <font color="#D7D75F"><b>&apos;post-create&apos; on &apos;/var/spool/abrt/ccpp-2021-12-01-16:19:03.60712-4600&apos; exited with 1</b></font>
ديسمبر 01 16:19:03 fedora abrt-server[4672]: <font color="#D7D75F"><b>Deleting problem directory &apos;/var/spool/abrt/ccpp-2021-12-01-16:19:03.60712-4600&apos;</b></font>
</pre>


`$ RUST_BACKTRACE=1 ./target/release/blue-recorder`
<pre>ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags=&apos;-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection&apos; --extra-ldflags=&apos;-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld &apos; --extra-cflags=&apos; -I/usr/include/rav1e&apos; --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librav1e --enable-libsmbclient --enable-version3 --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-vulkan --enable-libglslang --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-lv2 --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libmfx --enable-runtime-cpudetect
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
<span style="background-color:#1E1E1E"><font color="#FFFF00">Guessed Channel Layout for Input Stream #0.0 : stereo</font></span>
Input #0, pulse, from &apos;default&apos;:
  Duration: N/A, start: 1638393511.730760, bitrate: 1536 kb/s
  Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:
  Stream #0:0 -&gt; #0:0 (pcm_s16le (native) -&gt; vorbis (libvorbis))
Press [q] to stop, [?] for help
Output #0, ogg, to &apos;/home/suliman/الفيديو/dd.mkv.temp.audio&apos;:
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Audio: vorbis, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavc58.134.100 libvorbis
<span style="background-color:#1E1E1E"><font color="#00FFFF">[libvorbis @ 0x555a5800f9c0] </font></span><span style="background-color:#1E1E1E"><font color="#FFFF00">Queue input is backward in time</font></span>=1.03x    
size=      82kB time=00:00:08.00 bitrate=  83.8kbits/s speed=1.01x    
video:0kB audio:77kB subtitle:0kB other streams:0kB global headers:4kB muxing overhead: 5.813997%
Exiting normally, received signal 15.
thread &apos;main&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }&apos;, src/ffmpeg_interface.rs:368:18
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: blue_recorder::ffmpeg_interface::Ffmpeg::stop_record
   4: &lt;O as gtk::auto::button::ButtonExt&gt;::connect_clicked::clicked_trampoline
   5: g_signal_emit_valist
   6: g_signal_emit
   7: &lt;unknown&gt;
   8: g_closure_invoke
   9: &lt;unknown&gt;
  10: g_signal_emit_valist
  11: g_signal_emit
  12: &lt;unknown&gt;
  13: &lt;unknown&gt;
  14: g_signal_emit_valist
  15: g_signal_emit
  16: &lt;unknown&gt;
  17: g_cclosure_marshal_VOID__BOXEDv
  18: g_signal_emit_valist
  19: g_signal_emit
  20: &lt;unknown&gt;
  21: &lt;unknown&gt;
  22: &lt;unknown&gt;
  23: gtk_event_controller_handle_event
  24: &lt;unknown&gt;
  25: &lt;unknown&gt;
  26: g_signal_emit_valist
  27: g_signal_emit
  28: &lt;unknown&gt;
  29: &lt;unknown&gt;
  30: gtk_main_do_event
  31: &lt;unknown&gt;
  32: &lt;unknown&gt;
  33: g_main_context_dispatch
  34: &lt;unknown&gt;
  35: g_main_loop_run
  36: gtk_main
  37: blue_recorder::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault (core dumped)
</pre>

Hope this helps

**Comment by xlmnxp** [comment]
@me00001 I dig in the issue and I installed Fedora 35 for test, it look like they change `org.gnome.Shell.ScreenCast` api 
so it cannot stop recording
I will work to use freedesktop screencast for gnome and kde that will fix the issue and allow us to choose specify application in Wayland

**Comment by major-mayer** [comment]
That's great news, for me the screen record doesn't work either.
Thank you very much.

**Comment by seltzered** [comment]
See also https://github.com/SeaDve/Kooha/issues/120 , had the same issue under Gnome 40 (ubuntu 21.10)

**Comment by corradoventu** [comment]
Same problem also with blue-recorder flatpak

**Comment by xenithorb** [comment]
Still an issue.

**Comment by me00001** [comment]
> Same problem also with blue-recorder flatpak
> Still an issue.

Need someone to make PR for that, or wait @xlmnxp to fix this issue 

This is how free software works

**Comment by bartv42** [comment]
Still an issue.

**Comment by xlmnxp** [comment]
@bartv42 yes, we still working on Wayland support for gnome 40+

**Comment by xlmnxp** [comment]
fixed in #39
