### ISSUE TITLE
Do not replace files with the same name without asking

### ISSUE THREAD

**Issue by amir2mi** [xlmnxp/blue-recorder#22]
Hi, in my experience I have worked with dozens of recorder apps, Blue Recorder was the best so far.
However, the only annoying thing is replacing files with the same name.
By default, if the user does not enter the name of the file it will have DateTime as name, but if the user enters a name, the file will be saved with this name which is fine but if the user records again without changing the file name, the new file will replace the old file without even asking.
IMHO it can be fixed by adding a numeric suffix like `filename (1)`, `filename (2)`, `filename (3)` ... or asking for replacing the file with the same name.

**Comment by xlmnxp** [comment]
I added it but the release will be late a little because there other issue we work to fix,
anyway you can build it from source or use snap version channel `edge`
