### ISSUE TITLE
Do not overwrite by default

### ISSUE THREAD

**Issue by joeitu** [xlmnxp/blue-recorder#23]
Hello,

I had  90min important zoom meeting that I recorded with blue recorder.

At the end of the meeting, I go to the blue recorder window to stop the recording, when clicking nothing happens, the app has frozen.  So I double-click again.

Blue recorder stop freezing and I now realize that my extra clicks have stopped the recorder and started a new one with the same file name. It has overwritten my 90min recording for a 2sec recording of me clicking nervously on the Stop button. 

Software with data loss hazards should be strongly labeled as experimental, and should not be launched in the wild. I find it unacceptable that I found this software in PopOS software center.

For the sack of open-source reputation, please check if the file exists before writing to it and until then keep it away from software stores and package repositories.

**Comment by me00001** [comment]
This feature is available in the beta branch 
https://github.com/flathub/sa.sy.bluerecorder/tree/beta

But since blue recorder version hasn't changed yet 
https://github.com/xlmnxp/blue-recorder/blob/bacc198bd0d40c970abfd36742c1e8b700e5369f/Cargo.toml#L2-L3
i keep any update it to beta branch, and will merge it into master branch when the version is updated

**Comment by joeitu** [comment]
I think you should either update the master asap, or remove it from the flatpack repo to avoid any other data loss. When users download packages from flatpack they expect a certain software quality which includes overwriting prevention.

**Comment by xlmnxp** [comment]
@joeitu we will make a release today 0.1.5 for add this feature (which already requested from other users #22 and we add it),
sorry for lose your video by overwrite it

**Comment by xlmnxp** [comment]
snap version released to stable channel

**Comment by joeitu** [comment]
Awesome, thank you @xlmnxp :+1:

**Comment by xlmnxp** [comment]
flathub released 👍🏼 
can you test it @joeitu ?

**Comment by xlmnxp** [comment]
I think it fixed

**Comment by xlmnxp** [comment]
thank you @me00001 @joeitu

**Comment by joeitu** [comment]
Hmm Pop os shop tell me that the software is up to date, but the "about" button in blue recorder show me version `1.4` 
But I believe this issue rely on the pop shop side.

**Comment by xlmnxp** [comment]
> Hmm Pop os shop tell me that the software is up to date, but the "about" button in blue recorder show me version `1.4` But I believe this issue rely on the pop shop side.

sorry for that, I didn't change the version number in about dialog
but you can try record video and then try to overwrite it

**Comment by joeitu** [comment]
Yes it works ! :tada: 

Thanks for being so quick fixing that issue :ok_hand:

**Comment by xlmnxp** [comment]
> Yes it works ! tada
> 
> Thanks for being so quick fixing that issue ok_hand

Great 👍🏼
