### ISSUE TITLE
Add CI to project

### ISSUE THREAD

**Issue by qarmin** [xlmnxp/blue-recorder#24]
Currently there is no automatic way to check if app compile properly.

I found that `libappindicator3-1` in README is not proper(at least for Ubuntu 21.10), and `libappindicator3-dev` needs to be installed to be able to compile app - with CI I could just look at it to be sure at 100% what exactly requirements have this app.

Also CI will allow to produce compiled binaries which could be added release page

**Comment by xlmnxp** [comment]
there `snap/snapcraft.yaml` whick is compile automatically when new commit push to this git repo

I will try to use Github CI to do that
