### ISSUE TITLE
Blue Recorder not recording under Gnome Wayland Ubuntu 22.04 

### ISSUE THREAD

**Issue by corradoventu** [xlmnxp/blue-recorder#27]
In Ubuntu 22.04 Wayland session I start blue-recorder: installed:  0+git.b365de8 (127)
try select a window or an area, it does not select anything outside of its own window.
start recording: nothing recorded.
Note: same problem with blue-recorder 126

[journalctl.txt](https://github.com/xlmnxp/blue-recorder/files/7925784/journalctl.txt)

**Comment by me00001** [comment]
See https://github.com/xlmnxp/blue-recorder/issues/18 and https://github.com/xlmnxp/blue-recorder/issues/17
