### ISSUE TITLE
Capture area ... at position ... outside the screen size 3840x1080

### ISSUE THREAD

**Issue by danstewart** [xlmnxp/blue-recorder#28]
Having an issue with the "Area Chooser".
When it's near the bottom of the screen I get an error complaining the area is off the screen.

Here is the exact error:
```
[x11grab @ 0x55a0a1c9ea00] Capture area 397x299 at position 2691.795 outside the screen size 3840x1080
:99.0+2691,795: Invalid argument
```

And here is a screenshot of the captured area:
![image](https://user-images.githubusercontent.com/10670565/153453103-d9a5df92-872d-45f9-9fd8-4ff8b1853d09.png)

**Comment by xlmnxp** [comment]
2691 + 397 = 3088 < 3840
299 + 795 = 1094 > 1080 (this is the reason)
I think x11grab calculate window shadow as part of select area

**Comment by danstewart** [comment]
Looks like it, do you maybe need to remove the `depth` value?

`xwininfo` output for another failing example:
```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x7001c18 "Area Chooser"

  Absolute upper-left X:  2341
  Absolute upper-left Y:  297
  Relative upper-left X:  2341
  Relative upper-left Y:  297
  Width: 1163
  Height: 801
  Depth: 32
  Visual: 0x6ab
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x7000006 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +2341+297  -336+297  -336--18  +2341--18
  -geometry 1163x801+2341--18
```

**Comment by xlmnxp** [comment]
I don't know if depth is used for that?

**Comment by danstewart** [comment]
I can't find a definitive answer of what the `depth` value actually means.
Found a few forum posts using at as color depth but I don't think that's correct.

Testing on a few different windows I tend to get either 24 or 32.
Seems GTK apps are 32 and electron apps are 32.

**Comment by danstewart** [comment]
It does seem to be roughly correct, I put the area chooser at the bottom of the screen.

xwininfo:
```
  Absolute upper-left X:  2270
  Absolute upper-left Y:  810
  Relative upper-left X:  2270
  Relative upper-left Y:  810
  Width: 397
  Height: 299
  Depth: 32
```

Error:
```
[x11grab @ 0x55bcd20f1a00] Capture area 397x299 at position 2270.810 outside the screen size 3840x1080
```

299 + 810 = 1109
1109 - 32 = 1077

So there are 3px unaccounted for :man_shrugging:

**Comment by danstewart** [comment]
After some further testing maybe this isn't what is needed.

Some tests with a window aligned to the bottom of the screen:


<details>
<summary>Nautilus (Gnome Files)</summary>

```
  Absolute upper-left X:  2075
  Absolute upper-left Y:  647
  Relative upper-left X:  2075
  Relative upper-left Y:  647
  Width: 644
  Height: 495
  Depth: 32
```

647 + 495 = 1142
1142 - 32 = 1110
</details>



<details>
<summary>Gedit</summary>

```
  Absolute upper-left X:  2405
  Absolute upper-left Y:  257
  Relative upper-left X:  2405
  Relative upper-left Y:  257
  Width: 1058
  Height: 885
  Depth: 32
```

257 + 885 = 1142
1142 = 32 = 1110
</details>

<details>
<summary>VS Code</summary>
```
  Absolute upper-left X:  2722
  Absolute upper-left Y:  810
  Relative upper-left X:  10
  Relative upper-left Y:  39
  Width: 508
  Height: 270
  Depth: 24
```

810 + 270 = 1080
</details>

<details>
<summary>Spotify</summary>
```
  Absolute upper-left X:  2073
  Absolute upper-left Y:  146
  Relative upper-left X:  10
  Relative upper-left Y:  39
  Width: 1717
  Height: 934
  Depth: 24
```

146 + 934 = 1080
</details>

<details>
<summary>Area Chooser</summary>
```
  Absolute upper-left X:  2666
  Absolute upper-left Y:  810
  Relative upper-left X:  2666
  Relative upper-left Y:  810
  Width: 397
  Height: 299
  Depth: 32
```

810 + 299 = 1109
1109 - 32 = 1077
</details>
