### ISSUE TITLE
Make it clear which record mode is selected

### ISSUE THREAD

**Issue by danboid** [xlmnxp/blue-recorder#37]
It seems blue-recorder has two main record modes currently - window and area but the user has no way of telling which mode it is going to use when they hit record. The GUI needs to be changed somehow so that it is clear what is going to be recorded when they push record.

The most obvious and probably easiest to implement would be for either the 'Select a Window' or 'Select an area' button to be shown as depressed / selected (ie displayed in a slightly darker colour) to make it clear it is the currently selected record mode.

**Comment by xlmnxp** [comment]
I don't think it possible to implement it in correct UI

**Comment by xlmnxp** [comment]
added in #39
