### ISSUE TITLE
Hide Blue Recorder window on record start

### ISSUE THREAD

**Issue by moshfiqrony** [xlmnxp/blue-recorder#42]
Thanks for the great and lightweight recorder :)

This is my current Blue Record version
![image](https://user-images.githubusercontent.com/26689488/221764867-98080a52-f55d-484f-9e1c-8130183e2109.png)

It would be great if the recorder window get's minimized automatically when a record session starts. Also it would be a great touch if an splash screen for countdown appears.

**Comment by xlmnxp** [comment]
@moshfiqrony we already added a counter to the port of GTK4 which is WIP #39,
I'll work on the minimize option but I guess it won't be the default

**Comment by xlmnxp** [comment]
feature added in #39
