### ISSUE TITLE
No feedback for record button for audio-only recording

### ISSUE THREAD

**Issue by faveoled** [xlmnxp/blue-recorder#44]
![image](https://github.com/xlmnxp/blue-recorder/assets/85760289/6edfe2e7-2cb3-419a-942a-701c953d4ead)
1. Start the app
2. Disable "Record video"
3. Click "Record"
Expected condition: "Record" changed to "Stop recording". Actual: "Record" stays. Recording is done in the background (screenshot is after clicking the record button)

**Comment by xlmnxp** [comment]
I think already fixed in GTK4 port which still work in progress
#39

**Comment by xlmnxp** [comment]
fixed in #39
