### ISSUE TITLE
Record doesn't record anymore

### ISSUE THREAD

**Issue by dodalovicgran** [xlmnxp/blue-recorder#58]
Flatpak @Pop!_OS 22.04 LTS

0.2.0

Rebooting, reinstalling didn't help.

**Comment by xlmnxp** [comment]
@dodalovicgran can you share the terminal output?

**Comment by dodalovicgran** [comment]
i don't know how

**Comment by xlmnxp** [comment]
> i don't know how

run blue-recorder from terminal/console
```
flatpak run sa.sy.bluerecorder
```

**Comment by dodalovicgran** [comment]
I think it was related that the pluse audio was chosen in the dropdown, and I'm using pipewire or whatnot. We can close this. Thank you!
