### ISSUE TITLE
Cannot write output to /tmp directory with flatpak

### ISSUE THREAD

**Issue by mr337** [xlmnxp/blue-recorder#65]
Version: 0.2.0 via flatpak

When setting do a different directory than default get the following error when trying to record. In this case was trying to have output to `/tmp`.

```
/run/user/1000/doc/9deee15e/tmp/testgif.mp4.temp.without.audio.mp4: Permission denied
```

Using the default directory of Video does seem to work. I don't have a Video directory but still write the final file to my home directory.

**Comment by mr337** [comment]
That is fantastic, I think I maybe used to snaps where the dev or maintainer can only tweak/grant settings.

Thanks!

**Comment by xlmnxp** [comment]
you are welcome
