### ISSUE TITLE
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os

### ISSUE THREAD

**Issue by siduck76** [xlmnxp/blue-recorder#7]
![image](https://user-images.githubusercontent.com/59060246/118821143-9528f900-b8d4-11eb-8656-f4e3e412e70e.png)

**Comment by xlmnxp** [comment]
Do you have a sound sources in your system?

**Comment by siduck76** [comment]
sound source? you mean alsa or pulseaudio?

**Comment by xlmnxp** [comment]
> sound source? you mean alsa or pulseaudio?

PluseAudio or PipeWire
Do
```
pactl list sources
```

**Comment by siduck76** [comment]
Oh I use alsa :(

**Comment by xlmnxp** [comment]
Will ffmpeg record audio in your session without any issue?
try
```
ffmpeg -f alsa -i default -f ogg test.ogg
```

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/118937978-bc7ed500-b96b-11eb-9e03-be058a5cf71b.png)

**Comment by xlmnxp** [comment]
> ![image](https://user-images.githubusercontent.com/59060246/118937978-bc7ed500-b96b-11eb-9e03-be058a5cf71b.png)

not able to find alsa/PulseAudio

**Comment by siduck76** [comment]
I dont record audio anyways , simplescreenrecorder doesnt does this.

**Comment by xlmnxp** [comment]
> I dont record audio anyways , simplescreenrecorder doesnt does this.

It show error because you don't have audio input, I will fix that
it will not show error if you don't have any audio sources

**Comment by xlmnxp** [comment]
fixed 😄 , can you try it?

**Comment by siduck76** [comment]
> fixed  , can you try it?

it opens now but I get this error after I press the record button 

![image](https://user-images.githubusercontent.com/59060246/118952494-a1b35d00-b979-11eb-8da4-37d27b12d340.png)

**Comment by siduck76** [comment]
> > fixed  , can you try it?
 
 
![image](https://user-images.githubusercontent.com/59060246/118952852-e808bc00-b979-11eb-8cf9-1c8f7eb6db38.png)

 it opens now but I get this error after I press the record button
 
> ![image](https://user-images.githubusercontent.com/59060246/118952494-a1b35d00-b979-11eb-8da4-37d27b12d340.png)

**Comment by xlmnxp** [comment]
what is your session?

**Comment by siduck76** [comment]
Bspwm

**Comment by xlmnxp** [comment]
> Bspwm

I already pushed fix for it, did you see it?
