### ISSUE TITLE
Does not work on Fedora 34

### ISSUE THREAD

**Issue by andypillip** [xlmnxp/blue-recorder#8]
It seems the application doesn't work on Fedora 34.

After clicking Stop Recording, nothing happens. The Play button doesn't open anything, except providing the following error:

> Failed to open '/home/andy/Videos/2021-05-20 15:05:25.225362309.mkv': No such file or directory

When starting up, there are several messages due to missing modules:
 
> Gtk-Message: 17:04:45.613: Failed to load module "canberra-gtk-module"
> Gtk-Message: 17:04:45.613: Failed to load module "pk-gtk-module"
> Gtk-Message: 17:04:45.614: Failed to load module "canberra-gtk-module"
> Gtk-Message: 17:04:45.614: Failed to load module "pk-gtk-module"

Now, I read about installing "missing dependencies" in the readme. Isn't the whole point of Flatpak to provide applications, including their dependencies, to run on a variety of systems?

**Comment by xlmnxp** [comment]
It will work if you specify name then autogenerated one

There problem in name with timespan but I will fix it soon

**Comment by xlmnxp** [comment]
> Gtk-Message: 17:04:45.613: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:04:45.613: Failed to load module "pk-gtk-module"
Gtk-Message: 17:04:45.614: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:04:45.614: Failed to load module "pk-gtk-module"

This is normal and it come from gtk

**Comment by andypillip** [comment]
Sorry, but it's exactly the same if I specify a filename.

Failed to open '/home/andy/Videos/session.mkv': No such file or directory

**Comment by andypillip** [comment]
No, it's not in the directory.

Before there was a 0 KB temp file, but I cannot reproduce a situation where it's being created any more.

Blue recorder does support Wayland, right?

**Comment by xlmnxp** [comment]
> No, it's not in the directory.
> 
> Before there was a 0 KB temp file, but I cannot reproduce a situation where it's being created any more.
> 
> Blue recorder does support Wayland, right?

Yeah, I think Wayland version is out of date

@me00001 can you update it?

**Comment by me00001** [comment]
> No, it's not in the directory.
> 
> Before there was a 0 KB temp file, but I cannot reproduce a situation where it's being created any more.
> 
> Blue recorder does support Wayland, right?

Maybe something has changed in Gnome Shell, i found error come from pipewire with `journalctl -f` command  

The error comes after pressing the record button, happening with  building from source or Flatpak build with the same error  

<pre>مايو 21 15:24:39 me dbus-daemon[1071]: [session uid=1000 pid=1071] Activating service name=&apos;org.gnome.Shell.Screencast&apos; requested by &apos;:1.766&apos; (uid=1000 pid=299426 comm=&quot;./target/release/blue-recorder &quot;)
مايو 21 15:24:39 me dbus-daemon[1071]: [session uid=1000 pid=1071] Successfully activated service &apos;org.gnome.Shell.Screencast&apos;
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 2        (Spa:Enum:MediaType:video)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:None, flags 00000000 20 4</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Id 2        (Spa:Enum:VideoFormat:I420)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16x16</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16x16</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Rectangle 16383x16383</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 2147483647/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:None, flags 00000000 24 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 2        (Spa:Enum:MediaType:video)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 1        (Spa:Enum:MediaSubtype:raw)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Id 8        (Spa:Enum:VideoFormat:BGRx)</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Rectangle 1920x1080</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Fraction 0/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>  Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>    Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 1/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>      Fraction 60/1</b></font>
مايو 21 15:24:39 me pipewire[1738]: <font color="#EF2929"><b>(34.0 -&gt; 37.0) negotiating -&gt; error (no more input formats)</b></font>
مايو 21 15:24:39 me pipewire-media-session[1739]: <font color="#D7D75F"><b>can&apos;t link 34:35 -&gt; 37:38: no more input formats</b></font>
مايو 21 15:24:39 me pipewire-media-session[1739]: <font color="#D7D75F"><b>error id:31 seq:1143 res:-22 (Invalid argument): no more input formats</b></font>
مايو 21 15:24:41 me dbus-daemon[1071]: [session uid=1000 pid=1071] Activating via systemd: service name=&apos;org.freedesktop.Tracker3.Miner.Extract&apos; unit=&apos;tracker-extract-3.service&apos; requested by &apos;:1.144&apos; (uid=1000 pid=9009 comm=&quot;/usr/lib/tracker-miner-fs-3 &quot;)
</pre>

**Comment by me00001** [comment]
> > No, it's not in the directory.
> > Before there was a 0 KB temp file, but I cannot reproduce a situation where it's being created any more.
> > Blue recorder does support Wayland, right?
> 
> Yeah, I think Wayland version is out of date
> 
> @me00001 can you update it?

It's here 
https://github.com/flathub/sa.sy.bluerecorder/pull/2#issuecomment-845854332

**Comment by xlmnxp** [comment]
Is it appear in the new version, if yes then try to change the recording format to webm and tell us

**Comment by xlmnxp** [comment]
@andypillip Is the issue fix?

**Comment by andypillip** [comment]
So, my Flatpak version is up to date from stable (0.1.4). I tried to install the linked version but it gives a 404.

I noticed two other things:
* There is no option for WebM
* If I choose "Select Window", only Thunderbird provides a crosshair mouse cursor, not Terminal, Nautilus or Firefox

Is this expected due to the outdated version?

**Comment by xlmnxp** [comment]
> So, my Flatpak version is up to date from stable (0.1.4). I tried to install the linked version but it gives a 404.
> 
> I noticed two other things:
> 
>     * There is no option for WebM
> 
>     * If I choose "Select Window", only Thunderbird provides a crosshair mouse cursor, not Terminal, Nautilus or Firefox
> 
> 
> Is this expected due to the outdated version?

there no WebM option yet but I will work to add it
Select Window use `xwininfo` so only xorg application can be selected (I will provide better way)

**Comment by xlmnxp** [comment]
> So, my Flatpak version is up to date from stable (0.1.4). I tried to install the linked version but it gives a 404.
> 
> I noticed two other things:
> 
>     * There is no option for WebM
> 
>     * If I choose "Select Window", only Thunderbird provides a crosshair mouse cursor, not Terminal, Nautilus or Firefox
> 
> 
> Is this expected due to the outdated version?

blue-recorder@0.1.4 is latest version
