### ISSUE TITLE
A bit slow when recording at 60 FPS 

### ISSUE THREAD

**Issue by siduck76** [xlmnxp/blue-recorder#9]
the video output looks a bit slow / sluggish when recording at 60 FPS 

blue-recorder 

https://user-images.githubusercontent.com/59060246/119021301-e7dde000-b9bc-11eb-9df1-c50bc410fdfd.mp4

settings : 

![image](https://user-images.githubusercontent.com/59060246/119021436-0cd25300-b9bd-11eb-9976-7a719526d792.png)

Simple screen recorder 

https://user-images.githubusercontent.com/59060246/119021327-ef9d8480-b9bc-11eb-8ac6-f2cff3d77c03.mp4

**Comment by xlmnxp** [comment]
what is the output in the terminal when you start recording

**Comment by siduck76** [comment]
no output , try simplescreenrecorder at 60fps and compare it with blue-recorder.

**Comment by JLuc** [comment]
When saving, it takes ages to save when the recording is longer than a couple of seconds or 1 minute. And during all this time, there is no sign that something is happening : Blue Recorder looks frozen. Ubuntu 24.04 also warns about this and asks "Do you want to kill this frozen app ?". 
By chance, when i dont kill the app, it looks like "it works" under the freeze : a file is saved, and Blue Recorder comes back to life.

It would help trust when Blue Recorder would change its state while saving, eg showing a clock or even better : some evolving percentage sign...
